name: flutter_openvpn
description: Flutter OpenVPN uses OpenVpn Protocol to connect with ovpn file configurations.
version: 0.2.0
homepage: https://gitlab.com/topfreelancerdeveloper/flutter_openvpn.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1
  shared_preferences: ^0.5.12+4
  streaming_shared_preferences:
    git:
      url: https://gitlab.com/topfreelancerdeveloper/streaming_shared_preferences.git

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        package: com.topfreelancerdeveloper.flutter_openvpn
        pluginClass: FlutterOpenvpnPlugin
      ios:
        pluginClass: FlutterOpenvpnPlugin
